/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CompanyDTO
 */
export interface CompanyDTO {
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  type: CompanyDTOTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  address: string;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  contactNumber: string;
  /**
   *
   * @type {string}
   * @memberof CompanyDTO
   */
  email: string;
}

/**
 * @export
 * @enum {string}
 */
export enum CompanyDTOTypeEnum {
  StorageFacility = "STORAGE_FACILITY",
  Supplier = "SUPPLIER",
  Manufacturer = "MANUFACTURER",
  Retailer = "RETAILER",
}
