/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductItemDTO } from "./product-item-dto";

/**
 *
 * @export
 * @interface CourierProductItemsDTO
 */
export interface CourierProductItemsDTO {
  /**
   *
   * @type {Array<ProductItemDTO>}
   * @memberof CourierProductItemsDTO
   */
  inTransitToStorageFacilityProductItems: Array<ProductItemDTO>;
  /**
   *
   * @type {Array<ProductItemDTO>}
   * @memberof CourierProductItemsDTO
   */
  inTransitToBuyerProductItems: Array<ProductItemDTO>;
  /**
   *
   * @type {Array<ProductItemDTO>}
   * @memberof CourierProductItemsDTO
   */
  toBePickedUpProductItems: Array<ProductItemDTO>;
  /**
   *
   * @type {Array<ProductItemDTO>}
   * @memberof CourierProductItemsDTO
   */
  returningProductItems: Array<ProductItemDTO>;
}
