/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompanyDTO } from "./company-dto";
import { OrderItemDTO } from "./order-item-dto";

/**
 *
 * @export
 * @interface OrderItemGroup
 */
export interface OrderItemGroup {
  /**
   *
   * @type {CompanyDTO}
   * @memberof OrderItemGroup
   */
  company: CompanyDTO;
  /**
   *
   * @type {Array<OrderItemDTO>}
   * @memberof OrderItemGroup
   */
  orderItems: Array<OrderItemDTO>;
  /**
   *
   * @type {number}
   * @memberof OrderItemGroup
   */
  total: number;
}
