/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompanyDTO } from "./company-dto";
import { ProductItemDTO } from "./product-item-dto";

/**
 *
 * @export
 * @interface TransactionDTO
 */
export interface TransactionDTO {
  /**
   *
   * @type {string}
   * @memberof TransactionDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TransactionDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof TransactionDTO
   */
  updatedAt: string;
  /**
   *
   * @type {Array<ProductItemDTO>}
   * @memberof TransactionDTO
   */
  productItems: Array<ProductItemDTO>;
  /**
   *
   * @type {CompanyDTO}
   * @memberof TransactionDTO
   */
  sendingCompany?: CompanyDTO;
  /**
   *
   * @type {CompanyDTO}
   * @memberof TransactionDTO
   */
  receivingCompany?: CompanyDTO;
}
