/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompanyDTO } from './company-dto';
import { OrderItemDTO } from './order-item-dto';

/**
 *
 * @export
 * @interface OrderDTO
 */
export interface OrderDTO {
  /**
   *
   * @type {string}
   * @memberof OrderDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof OrderDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof OrderDTO
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof OrderDTO
   */
  status: OrderDTOStatusEnum;
  /**
   *
   * @type {number}
   * @memberof OrderDTO
   */
  total: number;
  /**
   *
   * @type {Array<OrderItemDTO>}
   * @memberof OrderDTO
   */
  orderItems: Array<OrderItemDTO>;
  /**
   *
   * @type {CompanyDTO}
   * @memberof OrderDTO
   */
  fromCompany?: CompanyDTO;
  /**
   *
   * @type {CompanyDTO}
   * @memberof OrderDTO
   */
  toCompany?: CompanyDTO;
}

/**
 * @export
 * @enum {string}
 */
export enum OrderDTOStatusEnum {
  Pending = 'PENDING',
  Invoiced = 'INVOICED',
  Paid = 'PAID',
}
