/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderDTO } from './order-dto';

/**
 *
 * @export
 * @interface PaymentDTO
 */
export interface PaymentDTO {
  /**
   *
   * @type {string}
   * @memberof PaymentDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof PaymentDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof PaymentDTO
   */
  updatedAt: string;
  /**
   *
   * @type {number}
   * @memberof PaymentDTO
   */
  amount: number;
  /**
   *
   * @type {OrderDTO}
   * @memberof PaymentDTO
   */
  order?: OrderDTO;
  /**
   *
   * @type {string}
   * @memberof PaymentDTO
   */
  orderId: string;
}
