/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProductItemByStatusDTO
 */
export interface ProductItemByStatusDTO {
  /**
   *
   * @type {Array<string>}
   * @memberof ProductItemByStatusDTO
   */
  status: Array<ProductItemByStatusDTOStatusEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum ProductItemByStatusDTOStatusEnum {
  InStorage = 'IN_STORAGE',
  OnHold = 'ON_HOLD',
  ToBePickedUp = 'TO_BE_PICKED_UP',
  InTransitToStorageFacility = 'IN_TRANSIT_TO_STORAGE_FACILITY',
  InStorageFacility = 'IN_STORAGE_FACILITY',
  InTransitToBuyer = 'IN_TRANSIT_TO_BUYER',
  Complete = 'COMPLETE',
  Canceled = 'CANCELED',
  RedFlag = 'RED_FLAG',
  ReturnRequested = 'RETURN_REQUESTED',
  ReturnAccepted = 'RETURN_ACCEPTED',
  ReturnRejected = 'RETURN_REJECTED',
  InTransitToSeller = 'IN_TRANSIT_TO_SELLER',
  Returned = 'RETURNED',
}
