/* tslint:disable */
/* eslint-disable */
/**
 * LogisTech
 * API for LogisTech
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateOrderStatusDTO
 */
export interface UpdateOrderStatusDTO {
  /**
   *
   * @type {string}
   * @memberof UpdateOrderStatusDTO
   */
  status: UpdateOrderStatusDTOStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateOrderStatusDTOStatusEnum {
  Pending = 'PENDING',
  Invoiced = 'INVOICED',
  Paid = 'PAID',
  Overdue = 'OVERDUE',
}
